### ISSUE TITLE
Bracket handling breaks on media queries

### ISSUE THREAD

**Issue by JohnMav** [kagbulos/CSSChecker#2]
Freaks out about about brackets on media queries.

e.g try out 

``` css
@media (max-width: 767px) {
    .block {
        margin-left: -20px;
        margin-right: -20px;
    }
}
```
